# Generated by Django 4.0.1 on 2022-01-23 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=128)),
                ('idade', models.IntegerField(blank=True, db_column='idade', null=True)),
                ('expertise', models.CharField(db_column='expertise', max_length=256)),
            ],
            options={
                'db_table': 'equipe',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('servico', models.CharField(db_column='servico', max_length=100)),
                ('descricao_servico', models.CharField(db_column='descricao_servico', max_length=512)),
            ],
            options={
                'db_table': 'servico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(blank=True, db_column='data_criacao', default=datetime.datetime.now)),
                ('data_postagem', models.DateTimeField(blank=True, db_column='data_postagem', null=True)),
                ('titulo', models.CharField(db_column='titulo', max_length=40)),
                ('texto', models.TextField()),
                ('tags', models.CharField(blank=True, db_column='tags', max_length=100, null=True)),
                ('autor_postagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor_postagem', to='CRUD.equipe')),
            ],
            options={
                'db_table': 'postagem',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='equipe_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipe_servico', to='CRUD.servico'),
        ),
    ]
